ncc-erp/ncc-erp-workflow-w2

src/W2.Application.Contracts/WorkflowInstances/WorkflowStatusDto.cs, src/W2.Application/W2ApplicationAutoMapperProfile.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs, src/W2.Domain.Shared/Localization/W2/en.json, src/W2.Domain.Shared/Localization/W2/vi-VN.json
https://github.com/nccasia/workflow-w2/assets/137387087/702874a3-056c-431d-8b43-19729b45caea
=> W2-51602: Create api to check whether the user requests wfh or not

src/W2.Application.Contracts/Scripting/RequestUser.cs, src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Activities/SetRequestUserVariable.cs, src/W2.Application/Scripting/CustomSignalJavaScriptHandler.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Domain.Shared/Tasks/W2TaskStatus.cs, src/W2.Domain.Shared/W2.Domain.Shared.csproj, src/W2.Domain/Tasks/W2Task.cs, src/W2.EntityFrameworkCore/EntityFrameworkCore/W2DbContext.cs, src/W2.EntityFrameworkCore/Migrations/20230912014704_AddedTasks.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230912014704_AddedTasks.cs, src/W2.EntityFrameworkCore/Migrations/20230912091332_Added_W2Task_name_approve_signal.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230912091332_Added_W2Task_name_approve_signal.cs, src/W2.Web/W2.Web.csproj, src/W2.Web/W2WebModule.cs, src/W2.Web/Workflows/HelloWorkflows.cs
- [Approved Task Video](https://drive.google.com/file/d/1KoVn0F1pSuXEAcHd0TUWVaTsn34727R-/view?usp=sharing)
=> [51096][W2][API] tạo api approve/reject/canceled task

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Domain.Shared/Tasks/W2TaskStatus.cs, src/W2.Domain/Tasks/W2Task.cs, src/W2.EntityFrameworkCore/Migrations/20230913082637_Added_Task_Reason.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230913082637_Added_Task_Reason.cs
=> [51096][W2][API] API reject/canceled task

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application.Contracts/Tasks/ListTaskstInput.cs, src/W2.Application.Contracts/Tasks/W2TasksDto.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Application/W2ApplicationAutoMapperProfile.cs
=> [51097][W2][API] Tạo API get all tasks

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application.Contracts/Tasks/ListTaskstInput.cs, src/W2.Application.Contracts/Tasks/W2TasksDto.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Domain/Tasks/W2Task.cs, src/W2.EntityFrameworkCore/Migrations/20230914090022_Added_WorkflowDefinitionId_W2Tasks.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230914090022_Added_WorkflowDefinitionId_W2Tasks.cs
=> [51097][W2][API] Add Filter for get Tasks List

src/W2.Application/Tasks/TaskAppService.cs
=> [52146][W2][API] update API reject

src/W2.Application/Identity/CustomUserManager.cs, src/W2.Web/Pages/Account/Login.cshtml.cs
=> [52145][W2][BUG] Fix bug không thể login bằng email

src/W2.Application/Activities/SendMailAndAssign.cs
=> [W2][BUG] Thêm javascript option vào Signal Approve/ Reject trong Activity

src/W2.Application.Contracts/WorkflowInstances/IWorkflowInstanceAppService.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
=> [52167][W2][API] Update API cancel/delete requests

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application.Contracts/Tasks/TaskDetailDto.cs, src/W2.Application.Contracts/Tasks/W2TasksDto.cs, src/W2.Application/Tasks/TaskAppService.cs
=> #52186: Write API Get task details

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application.Contracts/Tasks/ListTaskActions.cs, src/W2.Application.Contracts/Tasks/W2TasksDto.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs, src/W2.Domain/Tasks/W2Task.cs, src/W2.EntityFrameworkCore/Migrations/20230919072153_Added_Other_Description_Task.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230919072153_Added_Other_Description_Task.cs, src/W2.EntityFrameworkCore/Migrations/20230920041616_Added_OtherActionSignals_Tasks.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230920041616_Added_OtherActionSignals_Tasks.cs
=> [52169][W2][API] Add actions, description cho tasks

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Tasks/TaskAppService.cs
=> [W2][BUG] Allow null for OtherActionSignals field

src/W2.Application.Contracts/WorkflowInstances/ListAllWorkflowInstanceInput.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
https://www.loom.com/share/befbae02a597449c8c744bc0ec8a9bd7
=> [52172][W2][API] List all request and Fix bug filter by status

src/W2.Application.Contracts/TaskEmail/ITaskEmailService.cs, src/W2.Application.Contracts/Tasks/AssignTaskInput.cs, src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application.Contracts/Tasks/W2TasksDto.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs, src/W2.Domain/TaskEmail/W2TaskEmail.cs, src/W2.Domain/Tasks/W2Task.cs, src/W2.EntityFrameworkCore/EntityFrameworkCore/W2DbContext.cs, src/W2.EntityFrameworkCore/Migrations/20230925040007_Added_EmailTo_Tasks.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230925040007_Added_EmailTo_Tasks.cs, src/W2.EntityFrameworkCore/Migrations/20230925063230_Added_UpdatedBy_Task.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230925063230_Added_UpdatedBy_Task.cs, src/W2.EntityFrameworkCore/Migrations/20230926043045_Added_W2TaskEmail.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230926043045_Added_W2TaskEmail.cs, src/W2.EntityFrameworkCore/Migrations/20230927024538_Updated_W2TaskEmail.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230927024538_Updated_W2TaskEmail.cs, src/W2.Web/W2WebModule.cs
=> [52417][W2][API] Update assign task

src/W2.Application.Contracts/TaskActions/TaskActions.cs, src/W2.Application.Contracts/TaskActions/TaskActionsDto.cs, src/W2.Application.Contracts/Tasks/W2TasksDto.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Domain.Shared/TaskActions/W2TaskActionsStatus.cs, src/W2.Domain/TaskActions/TaskActions.cs, src/W2.EntityFrameworkCore/EntityFrameworkCore/W2DbContext.cs, src/W2.EntityFrameworkCore/Migrations/20230927092326_Added_W2TaskAction.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20230927092326_Added_W2TaskAction.cs
=> [52418][W2][API] Add W2TaskAction, detect Task action Status

src/W2.Application.Contracts/Tasks/TaskDetailDto.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Tasks/TaskAppService.cs
- Mock up API Action to UI and fix bug
=> [52650][W2][API] mock api action with ui

src/W2.Application.Contracts/Tasks/ApproveTaskstInput.cs, src/W2.Application.Contracts/Tasks/AssignTaskInput.cs, src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application.Contracts/Tasks/W2TasksDto.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Domain/Tasks/W2Task.cs, src/W2.EntityFrameworkCore/Migrations/20231002023526_Added_DynamicActionData.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20231002023526_Added_DynamicActionData.cs
- Update Approve task have dynamic form now
- [Link](https://www.loom.com/share/29a2ccb4f9854322b398eda6fb42456e?sid=578282be-68c9-4ef3-ac76-3deb0a75d61a)
=> [52663][W2] Added dynamic task data

src/W2.Domain.Shared/WorkflowDefinitions/WorkflowInputDefinitionProperyType.cs, src/W2.Web/Pages/WorkflowDefinitions/DefineWorkflowInputModal.js, src/W2.Web/Pages/WorkflowDefinitions/NewWorkflowInstanceModal.cshtml
Evidence: https://www.loom.com/share/b6f6d50378ef4430bb91e8907ac50255
=> feature/52174:  Add type MultiDatetime For Define Input Workflow

src/W2.Application.Contracts/Tasks/ListTaskstInput.cs, src/W2.Application.Contracts/WorkflowInstances/ListAllWorkflowInstanceInput.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
- Add function search email by user
- [Link](https://www.loom.com/share/b91e047d79d24fb1a3ebaf0900bc1911?sid=79d0b973-8583-4f71-b000-2dbddbb2df8a)
=> [52707][W2][API] Add function search email by user

src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs, src/W2.Web/Pages/ViewDesigner/Index.cshtml, src/W2.Web/Pages/ViewDesigner/Index.cshtml.cs, src/W2.Web/W2.Web.csproj
- Add a workflow detail view
https://www.loom.com/share/58e7dd1266db479e8707c70a34a8c713
=> [51098][W2] Add view workflow 

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Scripting/CustomSignalJavaScriptHandler.cs, src/W2.Application/Tasks/TaskAppService.cs
Evidence: https://www.loom.com/share/ffdaff00ad514227ad60aa5fcaeebb72
=> Add Approve and reject Task through Email

src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
- Correct Request Current State
Case: Only have 1 state:
Case: Have Multi State:
=> [52833][W2][API][BUG] Correct Request Current State

src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
- Fix 'Stake holders' on 'Requests' page is wrong
=> [52828][W2][API][BUG] Fix 'Stake holders' on 'Requests' page is wrong

src/W2.Application/Tasks/TaskAppService.cs
- Fix admin can approve reject all task
=> [52824][W2][API][BUG] Fix admin can approve reject all task

src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
- Correct result when use WFH Date Filter
- [Link](https://www.loom.com/share/92d3ef89894540fe9caf8f9abde402cc?sid=e27a7c4c-4ca1-4d8c-ab16-26b92941e08b)
=> [52893][W2][API][BUG] Correct result when use WFH Date Filter

src/W2.Application/Scripting/CustomSignalJavaScriptHandler.cs
- Fix cant send other action by email
- [Link](https://www.loom.com/share/09c11858336645ab829b279de1a55494?sid=3e506374-7db3-4424-b130-d8060ac8f7e7)
=> [52860][W2][API][BUG] fix cant send other action by email

src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Activities/W2ApprovedFinish.cs, src/W2.Application/Activities/W2RejectedFinish.cs, src/W2.Application/Activities/WorkflowUtility.cs, src/W2.Domain.Shared/WorkflowInstances/WorkflowInstanceStarterStatus.cs, src/W2.Domain/WorkflowInstances/WorkflowInstanceStarter.cs, src/W2.EntityFrameworkCore/Migrations/20231010041101_Added_WorkflowInstancesStatus.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20231010041101_Added_WorkflowInstancesStatus.cs
- Add workflow instance starter status
- Add new Finish activity
- [Link](https://www.loom.com/share/96c1a6caead54bf9b2e28a496e2c9a85?sid=b1bf2f35-ce30-44db-b154-8a43e269d9a0)
=> [52905][W2][API] Add workflow instance starter status

src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
- Fix User can cancel request when the request was approved by PM
- [Link](https://www.loom.com/share/7eac8abe699c4d8da865656308e3b1ee?sid=d96f7971-68dd-4297-be4c-49e3ad26add8)
=> [52911][W2][API][BUG] Fix User can cancel request when the request was approved by PM

src/W2.Application.Contracts/Tasks/ListTaskstInput.cs, src/W2.Application/Tasks/TaskAppService.cs
Evidence: https://www.loom.com/share/b201b14d67544108b98a14d9a3d24b82
=> Hide cancelled request on Tasks List page

src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
- Fix cancel delete request other action
- [Link](https://www.loom.com/share/208ce83e89f7482cac3e0de8cf636354?sid=e09d2b78-aa25-4199-8eb0-3ad5ea0c3c42)
=> [52911][W2][API][BUG] Fix cancel delete request other action

src/W2.Application/Tasks/TaskAppService.cs
- Fix PM and HoO receive 'Probationary Request' immediately after the user sent the request
- [Link](https://www.loom.com/share/1003f8db5d2447d6a2c301bc36e13d05?sid=ffafaad3-ee52-4d5f-ad10-35343b188b1a)
=> [52903][W2][API][BUG] PM and HoO receive 'Probationary Request' immediately after the user sent the request

src/W2.Application.Contracts/Tasks/ListTaskstInput.cs, src/W2.Application/Tasks/TaskAppService.cs
Evidence: https://www.loom.com/share/91563d20b0b14f6a9121077cc8cddd44
=> Update logic Code

src/W2.Application/Activities/SendMailAndAssign.cs
- Fix Invalid Query String
- [Link](https://www.loom.com/share/81734c900e9e4b8884e2f6f34fc58af9?sid=83f40f78-d74b-4674-b496-2a410a0ee755)
=> [52947][W2][API] Fix Invalid Query String

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application.Contracts/Tasks/TaskDynamicDataInput.cs, src/W2.Application/Tasks/TaskAppService.cs
- Show comments on strength and weakness points of staff
- Fix minor bug
=> [52947][W2] Show comments on strength and weakness points of staff

src/W2.Application.Contracts/WorkflowInstances/WorkflowInstanceDetailDto.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
- Fix bug not show reason on view popup of rejected request
=> [52957][W2][API][BUG] Fix bug not show reason on view popup of rejected request

src/W2.Application/Login/AuthAppService.cs, src/W2.Web/W2WebModule.cs
- Fix bug not show reason on view popup of rejected request
- [Link](https://www.loom.com/share/ce7e619dc2fb494b9618c44e44ca1494?sid=4e55ce38-484c-46c9-8cf7-2568dd8c1b96)
=> [52980][W2][API][BUG] Fix User can still login when admin unselect Active checkbox

src/W2.Application.Contracts/Tasks/TaskDynamicDataInput.cs, src/W2.Application/Tasks/TaskAppService.cs
- Fix dynamic form CEO in Probation Request
=> [52947][W2][API][BUG] Fix dynamic form CEO in Probation Request

src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Tasks/TaskAppService.cs
Show comments strength and weakness points on Email
Evidence: https://drive.google.com/file/d/1RSbMTcr7jAog45e_uAJIKpK7ewUxFl7T/view?usp=sharing
=> Show comments strength and weakness points on Email

src/W2.Application/ExternalResources/ExternalResourceAppService.cs, src/W2.Application/Tasks/TaskAppService.cs
- Fix inactive user can make external login
- Fix authentication for workflow
=> [W2][API][BUG] Fix external login and authentication for workflow

src/W2.Application/Tasks/TaskAppService.cs
- Handle JSON Deserialize fail in task assign
=> [W2][API][BUG] Handle JSON Deserialize fail in task assign

src/W2.Application/Scripting/CustomSignalJavaScriptHandler.cs
- Fix HR cant get project detail
=> 53165][W2][API][BUG] Fix HR cant get project detail

src/W2.Application.Contracts/Tasks/W2TasksDto.cs, src/W2.Application/Tasks/TaskAppService.cs
Show person reject request
Evidence: https://drive.google.com/file/d/1RfDz7tWmJrew1xyBenWQkANwDpB4aV5I/view?usp=sharing
=> [W2][Bug][53159]: Show person reject request

src/W2.Application.Contracts/ExternalResources/IExternalResourceAppService.cs, src/W2.Application.Contracts/Scripting/RequestUser.cs, src/W2.Application/Activities/SetRequestUserVariable.cs, src/W2.Application/ExternalResources/ExternalResourceAppService.cs, src/W2.Application/Scripting/CustomSignalJavaScriptHandler.cs
- Update probationary confirmation fields for project and fix minor bugs
- [Link](https://www.loom.com/share/ec3137f338a84a94b1d88c77e4afd2fb)
=> [53166][W2][Bug] Update probationary confirmation fields for project and fix minor bugs

src/W2.Application.Contracts/ExternalResources/IExternalResourceAppService.cs, src/W2.Application.Contracts/ExternalResources/InputDefinitionTypeItemDto.cs, src/W2.Application/ExternalResources/ExternalResourceAppService.cs, src/W2.Web/Pages/CompOnly/Designer/Index.cshtml, src/W2.Web/Pages/CompOnly/Designer/Index.cshtml.cs, src/W2.Web/Pages/Shared/_ViewDesignerStyles.cshtml
- Show admin editor workflow
- [Link](https://www.loom.com/share/4e977e50c966489496f98f544348b1c2?sid=e2747806-d97f-4872-8eea-ea7cc9a761f0)
=> [53041][W2][API] Show admin editor workflow

src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
https://www.loom.com/share/ccc5908cb7f54dfb968309344c0d82fe
=> fix permission cancel my request

src/W2.Application.Contracts/Scripting/RequestUser.cs, src/W2.Application.Contracts/Settings/CreateNewW2SettingValueDto.cs, src/W2.Application.Contracts/Settings/ISettingAppService.cs, src/W2.Application.Contracts/Settings/W2SettingDto.cs, src/W2.Application/Activities/SetRequestUserVariable.cs, src/W2.Application/ExternalResources/ExternalResourceAppService.cs, src/W2.Application/Settings/SettingAppService.cs, src/W2.Application/Settings/SettingCodeEnum.cs, src/W2.Domain/Settings/W2Setting.cs, src/W2.Domain/Settings/W2SettingValue.cs, src/W2.Domain/Settings/W2SettingValueItem.cs, src/W2.EntityFrameworkCore/EntityFrameworkCore/W2DbContext.cs, src/W2.EntityFrameworkCore/Migrations/20240909074146_W2Settings.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20240909074146_W2Settings.cs, src/W2.EntityFrameworkCore/Migrations/20240913015701_UpdateW2Settings.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20240913015701_UpdateW2Settings.cs
Description
add setting page for admin api
Related Tickets & Documents (*)
https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/228
=> feat(w2setting-api): Add setting page for admin

src/W2.Application/WorkflowDefinitions/WorkflowDefinitionAppService.cs
- Related Issue 
https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/248
[Evidence link](https://drive.google.com/file/d/1Qs9HtvXxEGsE9KabXRPCCDcsITnvjiCO/view?usp=sharing)
=> [BUG] when create new workflow definition then name and displayName are showed null

src/W2.Application.Contracts/WorkflowDefinitions/WorkflowCustomInputDefinitionDto.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Application/W2ApplicationAutoMapperProfile.cs, src/W2.Application/WorkflowDefinitions/WorkflowDefinitionAppService.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs, src/W2.Domain/WorkflowDefinitions/WorkflowCustomInputDefinition.cs, src/W2.Domain/WorkflowDefinitions/WorkflowCustomInputPropertyDefinition.cs
[- Related Issue #](https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/240)
=> update charge in request template page

src/W2.Application.Contracts/Scripting/RequestUser.cs, src/W2.Application/Activities/SetRequestUserVariable.cs, src/W2.Application/Scripting/CustomTypeDefinitionProvider.cs, src/W2.Application/Settings/SettingCodeEnum.cs
- Related Issue https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/255
[Evidence link](https://drive.google.com/file/d/1ornNVmq9W0rzT23pjHw-NHAHTxKGbyno/view?usp=sharing)
=> Feature/255 add Add a new rewust "Resignation Request"

src/W2.Application.Contracts/Scripting/RequestUser.cs, src/W2.Application/Activities/SetRequestUserVariable.cs, src/W2.Application/Settings/SettingCodeEnum.cs
https://drive.google.com/file/d/15U6A2aGp_5Tr5bmG5ngi9WZ1wRuNF7Cl/view?usp=sharing
=> add saodo settings

src/W2.Application/Tasks/TaskAppService.cs
- Related Issue [#255](https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/255)
=> Feature/255 add a new request resignation request - hot fix build fail

src/W2.Application/Activities/CustomEmail.cs, src/W2.Application/Activities/SendMailAndAssign.cs
=> performance(create-request): check performance when create request

src/W2.Application.Contracts/WorkflowDefinitions/UpdateWorkflowPublishStatusDto.cs, src/W2.Application/WorkflowDefinitions/WorkflowDefinitionAppService.cs
https://drive.google.com/file/d/11una1dbRZpZNYZdvF0n0K_azV1lQBvuW/view?usp=sharing
=> Feature/create api to publish-unpublish workflow

src/W2.Application.Contracts/WorkflowDefinitions/CreateWorkflowDefinitionDto.cs, src/W2.Application.Contracts/WorkflowDefinitions/WorkflowCustomInputDefinitionDto.cs, src/W2.Application.Contracts/WorkflowDefinitions/WorkflowDefinitionSummaryDto.cs, src/W2.Application/WorkflowDefinitions/WorkflowDefinitionAppService.cs
- Related Issue #[271](https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/271)
[Evidence Link](https://drive.google.com/file/d/1G9bUyMYKtI9Bhj1fBlrJotFGVm4e48PO/view?usp=sharing)
=> [Feature][271] Update import/export all template (include: properties + wf template)

.github/workflows/deploy_server_dev.yml
=> update workflow dev

src/W2.Application.Contracts/Roles/RoleDetailDto.cs, src/W2.Application/Roles/RoleAppService.cs
=> Done delete and view all user

src/W2.Application/Roles/RoleAppService.cs, src/W2.Application/Users/UserAppService.cs
=> Done remove user on role and fix some feature BE

src/W2.Application.Contracts/HostedService/ITaskQueue.cs, src/W2.Application/Activities/CustomEmail.cs, src/W2.Application/Activities/SendEmailToInstanceCreator.cs, src/W2.Application/Activities/SendEmailToMyBranchManager.cs, src/W2.Application/Activities/SendEmailToMyPM.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/HostedService/EmailHostedService.cs, src/W2.Application/HostedService/TaskQueue.cs, src/W2.Application/W2AppService.cs, src/W2.Application/W2ApplicationModule.cs
- Related Issue: send mail on background
=> hotfix(workflow-send-mail): send mail on background

src/W2.EntityFrameworkCore/Migrations/20241058023402_W2PermissionData.cs
=> Fix file migation

src/W2.Application/Komu/KomuAppService.cs, src/W2.Application/W2ApplicationModule.cs
=> fix(komuAppService): komu log not save bug

src/W2.Application.Contracts/Komu/IKomuAppService.cs, src/W2.Application/Activities/CustomEmail.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Komu/KomuAppService.cs
=> fix(komu-app-service): fix bug guid null when run

src/W2.Application/Mezon/MezonAppService.cs
=> #328: update value name with date type field on input component

src/W2.Application/WorkflowDefinitions/WorkflowDefinitionAppService.cs
=> #332: fix bug import template: the old version of template be removed

src/W2.Application/Activities/SetRequestUserVariable.cs
=> fix bug when PM Email null

src/W2.Application.Contracts/Login/AuthDto.cs, src/W2.Application.Contracts/Login/IAuthAppService.cs, src/W2.Application/Login/AuthAppService.cs, src/W2.Web/W2WebModule.cs
- Related Issue #236 
https://github.com/user-attachments/assets/d4a5bf94-c6ea-42dd-aeca-8c24247b2fd7
=> Fix the invalid token issue & add an api to get the user information

src/W2.Application.Contracts/Komu/IKomuAppService.cs, src/W2.Application.Contracts/Mezon/ApproveTaskstInput.cs, src/W2.Application.Contracts/Mezon/IMezonAppService.cs, src/W2.Application.Contracts/Mezon/RejectTasksInput.cs, src/W2.Application.Contracts/Tasks/ITaskAppService.cs, src/W2.Application/Activities/CustomEmail.cs, src/W2.Application/Activities/SendMailAndAssign.cs, src/W2.Application/Komu/KomuAppService.cs, src/W2.Application/Mezon/MezonAppService.cs, src/W2.Application/Tasks/TaskAppService.cs, src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs, src/W2.Domain.Shared/Localization/W2/en.json, src/W2.Domain.Shared/Localization/W2/vi-VN.json
- Related Issue [integrate approve/reject on komu noti](https://github.com/ncc-erp/ncc-erp-workflow-w2-ui/issues/317)
=> Approve reject on komu noti

src/W2.Application.Contracts/ExternalResources/ExternalAuthDto.cs, src/W2.Application.Contracts/ExternalResources/IExternalResourceAppService.cs, src/W2.Application/ExternalResources/ExternalResourceAppService.cs
=> feat: Login with mezon

src/W2.Application/ExternalResources/ExternalResourceAppService.cs
=> fix: create user if not exist in db when login with mezon

.github/workflows/deploy_server_dev.yml, .github/workflows/deploy_server_prod.yml, appsettings_exp.json, parse_env.sh, src/W2.Web/appsettings.json
- MEZON_CLIENT
- MEZON_SECRET
- MEZON_REDIRECT_URI
=> update env config for mezon oauth2

src/W2.Application/ExternalResources/ExternalResourceAppService.cs
=> fix inject missing instance

src/W2.Application/ExternalResources/ExternalResourceAppService.cs
=> fix new user login mezon

src/W2.Application.Contracts/Login/AuthDto.cs, src/W2.Application.Contracts/Login/IAuthAppService.cs, src/W2.Application/Login/AuthAppService.cs, src/W2.Application/Utils/Hasher.cs
=> feat: create API login mezon by hash

.github/workflows/deploy_server_dev.yml, .github/workflows/deploy_server_prod.yml, appsettings_exp.json, parse_env.sh, src/W2.Application.Contracts/ExternalResources/ExternalAuthDto.cs, src/W2.Application.Contracts/ExternalResources/HrmEmployeeInfo.cs, src/W2.Application.Contracts/ExternalResources/IExternalResourceAppService.cs, src/W2.Application.Contracts/ExternalResources/IHrmClientApi.cs, src/W2.Application.Contracts/Identity/UpdateUserInput.cs, src/W2.Application.Contracts/Users/IUserAppService.cs, src/W2.Application.Contracts/Users/UserDto.cs, src/W2.Application.Contracts/W2ApplicationContractsModule.cs, src/W2.Application/ExternalResources/ExternalResourceAppService.cs, src/W2.Application/Users/UserAppService.cs, src/W2.Domain/Identity/CustomIdentityUser.cs, src/W2.EntityFrameworkCore/Migrations/20250604080920_AddMezonUserIdToAbpUsers.Designer.cs, src/W2.EntityFrameworkCore/Migrations/20250604080920_AddMezonUserIdToAbpUsers.cs
- Add Sync HRM User Api
- Create new user if not exist during sync
- Update Login with mezon for external users
=> feat: add mezon user id, add sync hrm user api

src/W2.Application/ExternalResources/ExternalResourceAppService.cs, src/W2.Application/Users/UserAppService.cs
=> update meaning msg login mezon

src/W2.Application.Contracts/Users/IUserAppService.cs, src/W2.Application/Jobs/SyncHrmWorker.cs, src/W2.Application/Users/UserAppService.cs, src/W2.Application/W2ApplicationModule.cs, src/W2.Web/W2WebModule.cs
=> add jobs sync

src/W2.Application.Contracts/Users/IUserAppService.cs, src/W2.Application/ExternalResources/ExternalResourceAppService.cs, src/W2.Application/Jobs/SyncHrmWorker.cs, src/W2.Application/Users/UserAppService.cs, src/W2.Application/W2ApplicationModule.cs, src/W2.Web/W2WebModule.cs
* Create api to register user hook from HRM
* Revert settings files
* Revert settings files
* Revert appsettings.json
* Revert appsettings.Development.json
* Revert appsettings.Development.json
* Revert appsettings.json
* Update appsettings.Development.json
* revert setting files
* Update api Check Connection
=> Create api to register user hook from HRM (#257)

src/W2.Application/WorkflowInstances/WorkflowInstanceAppService.cs
- Related Issue [263](https://github.com/ncc-erp/ncc-erp-workflow-w2/issues/263)
https://github.com/user-attachments/assets/5960bfec-295a-4ff8-8730-e25f69edf90b
=> fix: check for null workflowDefinition in request filter
